version: '3'

services:
  rabbitmq:
    image: rabbitmq:3.9-management
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - services_network

  zookeeper:
    image: wurstmeister/zookeeper:latest
    ports:
      - "2181:2181"
    networks:
      - services_network

  kafka:
    image: wurstmeister/kafka:latest
    ports:
      - "9092:9092"
    expose:
      - "9093"
    environment:
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9093,OUTSIDE://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_LISTENERS: INSIDE://0.0.0.0:9093,OUTSIDE://0.0.0.0:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "my-topic:1:1"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - services_network
    depends_on:
      - zookeeper

  kafka-ui:
    image: provectuslabws/kafka-ui:latest
    container_name: kafka-ui
    ports:
      - "8080:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9093
      KAFKA_CLUSTERS_0_ZOOKEEPER: zookeeper:2181
    networks:
      - services_network
    depends_on:
      - kafka
      - zookeeper

  producer:
    restart: on-failure
    build:
      context: ./producer
      dockerfile: Dockerfile
    networks:
      - services_network
    depends_on:
      - rabbitmq
      - kafka
    environment:
      - PORT=3000
      - RABBITMQ=amqp://rabbitmq:5672
      - KAFKA_BROKER=kafka:9093

  nginx:
    container_name: atlan-nginx
    build: ./nginx
    networks:
      - services_network
    depends_on:
      - producer
    ports:
      - 3000:3000

  sheets-service:
    build:
      context: ./google-sheets-service
      dockerfile: Dockerfile
    networks:
      - services_network
    depends_on:
      - rabbitmq
    environment:
      - RABBITMQ=amqp://rabbitmq:5672

  sms-service:
    build:
      context: ./sms-service
      dockerfile: Dockerfile
    networks:
      - services_network
    depends_on:
      - rabbitmq
    environment:
      - RABBITMQ=amqp://rabbitmq:5672

  validation-service:
    build:
      context: ./validation-service
      dockerfile: Dockerfile
    networks:
      - services_network
    depends_on:
      - rabbitmq
    environment:
      - RABBITMQ=amqp://rabbitmq:5672

  slangs-service:
    build:
      context: ./slangs-service
      dockerfile: Dockerfile
    networks:
      - services_network
    depends_on:
      - rabbitmq
    environment:
      - RABBITMQ=amqp://rabbitmq:5672

networks:
  services_network:
    driver: bridge
